# Generated by Django 5.0.2 on 2024-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('vendor', '0005_alter_openinghoursmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
    ]
