# Generated by Django 5.0.2 on 2024-05-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_total_data_ordermodel_vendors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='tax_data',
            field=models.JSONField(blank=True, help_text="Data format: {'tax_type':{'tax_percentage':'tax_amount'}}", null=True),
        ),
    ]
